### ISSUE TITLE
remove_from_collection取消某report的收藏 不应发送所在组名

### ISSUE THREAD

**Issue by yjw1029** [USTCSoftware2018/Backend-Legacy#46]
限定每个report只能收藏在一组
取消收藏时前端无法拿到所在组名

现在的格式如下
```json
{
 "id": 16,
 "collection": "chemistry"
}
```

**Comment by ksqsf** [comment]
如果一个report被collect到不同collection里应该如何处理？

**Comment by ksqsf** [comment]
修改为自动切换到新collection

**Comment by yjw1029** [comment]
取消收藏依然需要collection字段
collection: ["This field is required."]

**Comment by yjw1029** [comment]
应当允许用户设立多个分组进行收藏
但是一个报告只能被收藏进一个组里

**Comment by ksqsf** [comment]
早上忘了部署到服务器上……现在应该没问题了
